import { Lead, Deal, Task, Activity, Note, Employee, Contact, KPIMetrics } from '../types/crm';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    full_name: 'Sam',
    email: 'ashish@enterprise.com',
    role: 'manager',
    phone: '+91 98765 43210',
    target_revenue: 1000000,
    department: 'Sales & BD',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-002',
    full_name: 'Priya Patel',
    email: 'priya.p@enterprise.com',
    role: 'bde',
    phone: '+91 98765 43211',
    target_revenue: 750000,
    department: 'Enterprise Sales',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-003',
    full_name: 'Amit Verma',
    email: 'amit.v@enterprise.com',
    role: 'bde',
    phone: '+91 98765 43212',
    target_revenue: 600000,
    department: 'Inbound Sales',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-004',
    full_name: 'Sneha Rao',
    email: 'sneha.r@enterprise.com',
    role: 'bde',
    phone: '+91 98765 43213',
    target_revenue: 650000,
    department: 'SME Sales',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
  },
];

const now = new Date();
const daysAgo = (d: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - d);
  return date.toISOString();
};
const todayStr = now.toISOString().split('T')[0];
const yesterdayStr = daysAgo(1).split('T')[0];
const tomorrowStr = (() => {
  const d = new Date(now);
  d.setDate(d.getDate() + 1);
  return d.toISOString().split('T')[0];
})();

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-001',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@apexdynamics.com',
    phone: '+91 98201 44552',
    company: 'Apex Dynamics Pvt Ltd',
    designation: 'Director of Technology',
    status: 'interested',
    deal_value: 85000,
    source: 'LinkedIn',
    assigned_to: 'emp-001',
    assigned_to_name: 'Sam',
    last_contacted_at: daysAgo(2),
    notes_count: 3,
    created_at: daysAgo(14),
    industry: 'Software / SaaS',
    location: 'Bengaluru, India',
  },
  {
    id: 'lead-002',
    name: 'Sneha Kulkarni',
    email: 'sneha.k@cloudscale.io',
    phone: '+91 98112 33445',
    company: 'CloudScale Technologies',
    designation: 'VP of Engineering',
    status: 'proposal',
    deal_value: 140000,
    source: 'Website',
    assigned_to: 'emp-002',
    assigned_to_name: 'Priya Patel',
    last_contacted_at: daysAgo(1),
    notes_count: 2,
    created_at: daysAgo(20),
    industry: 'Cloud Infrastructure',
    location: 'Mumbai, India',
  },
  {
    id: 'lead-003',
    name: 'Vikram Malhotra',
    email: 'vikram.m@finedge.com',
    phone: '+91 98334 55667',
    company: 'FinEdge Systems',
    designation: 'Chief Technology Officer',
    status: 'negotiation',
    deal_value: 250000,
    source: 'Referral',
    assigned_to: 'emp-001',
    assigned_to_name: 'Sam',
    last_contacted_at: daysAgo(3),
    notes_count: 4,
    created_at: daysAgo(35),
    industry: 'Fintech / Banking',
    location: 'Delhi NCR, India',
  },
  {
    id: 'lead-004',
    name: 'Anita Desai',
    email: 'anita.d@retailpulse.ai',
    phone: '+91 98450 11223',
    company: 'RetailPulse Analytics',
    designation: 'Head of Product',
    status: 'stale',
    deal_value: 45000,
    source: 'Google Ads',
    assigned_to: 'emp-003',
    assigned_to_name: 'Amit Verma',
    last_contacted_at: daysAgo(8), // Stale > 7 days!
    notes_count: 1,
    created_at: daysAgo(25),
    industry: 'E-Commerce Analytics',
    location: 'Pune, India',
  },
  {
    id: 'lead-005',
    name: 'Rajesh Gupta',
    email: 'rajesh@logitechsolutions.in',
    phone: '+91 98770 99887',
    company: 'LogiTech Solutions',
    designation: 'Founder & CEO',
    status: 'won',
    deal_value: 90000,
    source: 'Website',
    assigned_to: 'emp-002',
    assigned_to_name: 'Priya Patel',
    last_contacted_at: daysAgo(4),
    notes_count: 5,
    created_at: daysAgo(45),
    industry: 'Logistics / Supply Chain',
    location: 'Hyderabad, India',
  },
  {
    id: 'lead-006',
    name: 'Meera Nair',
    email: 'meera.n@healthbridge.org',
    phone: '+91 98990 77665',
    company: 'HealthBridge Medical Solutions',
    designation: 'Chief Operating Officer',
    status: 'contacted',
    deal_value: 120000,
    source: 'Events',
    assigned_to: 'emp-004',
    assigned_to_name: 'Sneha Rao',
    last_contacted_at: daysAgo(11), // Stale > 7 days!
    notes_count: 2,
    created_at: daysAgo(18),
    industry: 'Healthcare Tech',
    location: 'Chennai, India',
  },
  {
    id: 'lead-007',
    name: 'Rohan Mehta',
    email: 'rohan.m@greenergy.co',
    phone: '+91 98221 88990',
    company: 'GreenEnergy Corp',
    designation: 'IT Director',
    status: 'new',
    deal_value: 65000,
    source: 'Cold Outreach',
    assigned_to: 'emp-001',
    assigned_to_name: 'Sam',
    last_contacted_at: daysAgo(0),
    notes_count: 0,
    created_at: daysAgo(1),
    industry: 'Renewable Energy',
    location: 'Ahmedabad, India',
  },
  {
    id: 'lead-008',
    name: 'Deepika Joshi',
    email: 'deepika.j@smartmatrix.io',
    phone: '+91 98665 44332',
    company: 'SmartMatrix Enterprise',
    designation: 'Procurement VP',
    status: 'won',
    deal_value: 180000,
    source: 'Referral',
    assigned_to: 'emp-002',
    assigned_to_name: 'Priya Patel',
    last_contacted_at: daysAgo(5),
    notes_count: 3,
    created_at: daysAgo(60),
    industry: 'Enterprise IT',
    location: 'Bengaluru, India',
  },
  {
    id: 'lead-009',
    name: 'Suresh Reddy',
    email: 'suresh@fastdelivery.in',
    phone: '+91 98443 22110',
    company: 'FastDelivery Express',
    designation: 'VP Operations',
    status: 'lost',
    deal_value: 55000,
    source: 'Website',
    assigned_to: 'emp-003',
    assigned_to_name: 'Amit Verma',
    last_contacted_at: daysAgo(15),
    notes_count: 2,
    created_at: daysAgo(30),
    industry: 'Logistics',
    location: 'Hyderabad, India',
  },
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-001',
    lead_id: 'lead-001',
    lead_name: 'Rahul Sharma',
    company: 'Apex Dynamics Pvt Ltd',
    title: 'Apex Dynamics Platform Expansion',
    value: 85000,
    stage: 'proposal',
    probability: 60,
    expected_close_date: tomorrowStr,
    assigned_to: 'emp-001',
    assigned_to_name: 'Sam',
    created_at: daysAgo(14),
  },
  {
    id: 'deal-002',
    lead_id: 'lead-002',
    lead_name: 'Sneha Kulkarni',
    company: 'CloudScale Technologies',
    title: 'CloudScale Multi-Seat License',
    value: 140000,
    stage: 'proposal',
    probability: 70,
    expected_close_date: daysAgo(-7).split('T')[0],
    assigned_to: 'emp-002',
    assigned_to_name: 'Priya Patel',
    created_at: daysAgo(20),
  },
  {
    id: 'deal-003',
    lead_id: 'lead-003',
    lead_name: 'Vikram Malhotra',
    company: 'FinEdge Systems',
    title: 'FinEdge Core Integration Suite',
    value: 250000,
    stage: 'negotiation',
    probability: 85,
    expected_close_date: daysAgo(-3).split('T')[0],
    assigned_to: 'emp-001',
    assigned_to_name: 'Sam',
    created_at: daysAgo(35),
  },
  {
    id: 'deal-005',
    lead_id: 'lead-005',
    lead_name: 'Rajesh Gupta',
    company: 'LogiTech Solutions',
    title: 'LogiTech Enterprise Annual Cloud',
    value: 90000,
    stage: 'closed_won',
    probability: 100,
    expected_close_date: daysAgo(4).split('T')[0],
    closed_at: daysAgo(4),
    assigned_to: 'emp-002',
    assigned_to_name: 'Priya Patel',
    created_at: daysAgo(45),
  },
  {
    id: 'deal-008',
    lead_id: 'lead-008',
    lead_name: 'Deepika Joshi',
    company: 'SmartMatrix Enterprise',
    title: 'SmartMatrix Global Rollout',
    value: 180000,
    stage: 'closed_won',
    probability: 100,
    expected_close_date: daysAgo(5).split('T')[0],
    closed_at: daysAgo(5),
    assigned_to: 'emp-002',
    assigned_to_name: 'Priya Patel',
    created_at: daysAgo(60),
  },
  {
    id: 'deal-009',
    lead_id: 'lead-009',
    lead_name: 'Suresh Reddy',
    company: 'FastDelivery Express',
    title: 'FastDelivery Dispatch Add-on',
    value: 55000,
    stage: 'closed_lost',
    probability: 0,
    expected_close_date: daysAgo(15).split('T')[0],
    closed_at: daysAgo(15),
    assigned_to: 'emp-003',
    assigned_to_name: 'Amit Verma',
    created_at: daysAgo(30),
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-001',
    lead_id: 'lead-001',
    lead_name: 'Rahul Sharma',
    assigned_to: 'emp-001',
    assigned_to_name: 'Sam',
    title: 'Follow up with Rahul regarding pricing approval',
    description: 'Rahul requested commercial tier discount for 50+ seats. Review quote with VP and confirm.',
    task_type: 'call',
    priority: 'high',
    due_date: todayStr,
    due_time: '11:00',
    is_completed: false,
    created_at: daysAgo(2),
  },
  {
    id: 'task-002',
    lead_id: 'lead-003',
    lead_name: 'Vikram Malhotra',
    assigned_to: 'emp-001',
    assigned_to_name: 'Sam',
    title: 'Send revised contract to Vikram Malhotra',
    description: 'Update SLA clause 4.2 as requested by FinEdge legal team.',
    task_type: 'email',
    priority: 'urgent',
    due_date: todayStr,
    due_time: '15:30',
    is_completed: false,
    created_at: daysAgo(1),
  },
  {
    id: 'task-003',
    lead_id: 'lead-004',
    lead_name: 'Anita Desai',
    assigned_to: 'emp-003',
    assigned_to_name: 'Amit Verma',
    title: 'Re-engage Anita Desai (Stale lead - 8 days no touch)',
    description: 'Lead is showing inactivity. Send feature update and check if requirements have evolved.',
    task_type: 'follow_up',
    priority: 'high',
    due_date: yesterdayStr, // OVERDUE!
    due_time: '14:00',
    is_completed: false,
    created_at: daysAgo(5),
  },
  {
    id: 'task-004',
    lead_id: 'lead-006',
    lead_name: 'Meera Nair',
    assigned_to: 'emp-004',
    assigned_to_name: 'Sneha Rao',
    title: 'Share compliance documentation with HealthBridge',
    description: 'HIPAA and ISO27001 audit summaries requested.',
    task_type: 'email',
    priority: 'medium',
    due_date: daysAgo(2).split('T')[0], // OVERDUE!
    due_time: '16:00',
    is_completed: false,
    created_at: daysAgo(6),
  },
  {
    id: 'task-005',
    lead_id: 'lead-007',
    lead_name: 'Rohan Mehta',
    assigned_to: 'emp-001',
    assigned_to_name: 'Sam',
    title: 'Schedule introductory discovery call with Rohan Mehta',
    description: 'Inquiry received via cold outreach response. Wants to explore renewables telemetry integration.',
    task_type: 'meeting',
    priority: 'medium',
    due_date: tomorrowStr,
    due_time: '10:00',
    is_completed: false,
    created_at: daysAgo(1),
  },
  {
    id: 'task-006',
    lead_id: 'lead-005',
    lead_name: 'Rajesh Gupta',
    assigned_to: 'emp-002',
    assigned_to_name: 'Priya Patel',
    title: 'Onboarding handover with customer success',
    description: 'Introduce CSM Sneha Rao and schedule kick-off workshop.',
    task_type: 'review',
    priority: 'low',
    due_date: daysAgo(3).split('T')[0],
    is_completed: true,
    completed_at: daysAgo(3),
    created_at: daysAgo(5),
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-001',
    lead_id: 'lead-001',
    lead_name: 'Rahul Sharma',
    performed_by: 'emp-001',
    performed_by_name: 'Sam',
    activity_type: 'call',
    summary: 'Discovery & pricing discussion with Rahul',
    details: 'Discussed 50-seat requirement. Rahul confirmed budget is approved up to ₹85,000. Requested proposal review by Wednesday.',
    duration_minutes: 24,
    created_at: daysAgo(2),
  },
  {
    id: 'act-002',
    lead_id: 'lead-001',
    lead_name: 'Rahul Sharma',
    performed_by: 'emp-001',
    performed_by_name: 'Sam',
    activity_type: 'email',
    summary: 'Sent official proposal and feature comparison',
    details: 'Emailed pricing breakdown and Enterprise security specifications.',
    created_at: daysAgo(3),
  },
  {
    id: 'act-003',
    lead_id: 'lead-001',
    lead_name: 'Rahul Sharma',
    performed_by: 'emp-001',
    performed_by_name: 'Sam',
    activity_type: 'meeting',
    summary: 'Technical architecture demonstration',
    details: 'Showed live API connectors and custom webhook integration. Technical team was satisfied.',
    duration_minutes: 45,
    created_at: daysAgo(7),
  },
  {
    id: 'act-004',
    lead_id: 'lead-003',
    lead_name: 'Vikram Malhotra',
    performed_by: 'emp-001',
    performed_by_name: 'Sam',
    activity_type: 'meeting',
    summary: 'Final contract negotiation with legal & finance',
    details: 'Resolved data residency terms. Waiting for final signed agreement.',
    duration_minutes: 60,
    created_at: daysAgo(3),
  },
  {
    id: 'act-005',
    lead_id: 'lead-002',
    lead_name: 'Sneha Kulkarni',
    performed_by: 'emp-002',
    performed_by_name: 'Priya Patel',
    activity_type: 'call',
    summary: 'Proposal review with VP Engineering',
    details: 'Sneha presented our solution to executive board. Very positive feedback.',
    duration_minutes: 30,
    created_at: daysAgo(1),
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'note-001',
    lead_id: 'lead-001',
    author_id: 'emp-001',
    author_name: 'Sam',
    content: 'Rahul is very responsive on WhatsApp. Prefers morning calls before 11:30 AM.',
    is_pinned: true,
    created_at: daysAgo(10),
  },
  {
    id: 'note-002',
    lead_id: 'lead-001',
    author_id: 'emp-001',
    author_name: 'Sam',
    content: 'Key decision maker is VP Tech Sandeep Verma who will sign off on Friday.',
    is_pinned: false,
    created_at: daysAgo(4),
  },
  {
    id: 'note-003',
    lead_id: 'lead-003',
    author_id: 'emp-001',
    author_name: 'Sam',
    content: 'FinEdge has strict RBI compliance guidelines. Cloud hosting must be in Mumbai AWS region.',
    is_pinned: true,
    created_at: daysAgo(20),
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cnt-001',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@apexdynamics.com',
    phone: '+91 98201 44552',
    company: 'Apex Dynamics Pvt Ltd',
    designation: 'Director of Technology',
    linked_lead_id: 'lead-001',
    created_at: daysAgo(14),
  },
  {
    id: 'cnt-002',
    name: 'Sneha Kulkarni',
    email: 'sneha.k@cloudscale.io',
    phone: '+91 98112 33445',
    company: 'CloudScale Technologies',
    designation: 'VP of Engineering',
    linked_lead_id: 'lead-002',
    created_at: daysAgo(20),
  },
  {
    id: 'cnt-003',
    name: 'Vikram Malhotra',
    email: 'vikram.m@finedge.com',
    phone: '+91 98334 55667',
    company: 'FinEdge Systems',
    designation: 'Chief Technology Officer',
    linked_lead_id: 'lead-003',
    created_at: daysAgo(35),
  },
  {
    id: 'cnt-004',
    name: 'Anita Desai',
    email: 'anita.d@retailpulse.ai',
    phone: '+91 98450 11223',
    company: 'RetailPulse Analytics',
    designation: 'Head of Product',
    linked_lead_id: 'lead-004',
    created_at: daysAgo(25),
  },
];
